spring.application.name=sb.ecom
spring.ina.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testDB
spring.ina.show.sgl=true\
  spring.jpa.properties.hibernate.format_sql=true
spring.datasource.initialize=false
project.image=images/