spring.application.name=sb.ecom
spring.ina.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.ina.show.sgl=true
spring.ipa.properties.hibernate.foctoat..sql=true